### ISSUE TITLE
[10k]: Infrastructure-as-Code

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#123]
### Description

This is the high level milestone that ensures we're using IaC for cloud management and deployment strategy.  All of our updates will be done by code / Terraform so there are no manual deployments of infrastructure. 

### Definition of Done

- [x] IaC is documented in ADR
- [x] Initial IaC tools are added to the project
- [x] Deployment to lower environment tested through continuous integration
- [x] IaC tools and deployment process is documented

### Sub-tasks
- [x] #93 
- [x] #111  
- [x] #307  
- [ ] #332 (moved to Static Site - Post Launch Technical Improvements)
