### ISSUE TITLE
[Task]: Update CONTRIBUTING.md with results of branch ADR and with open source runbook content

### ISSUE THREAD

**Issue by acouch** [HHS/grants-equity#416]
### Summary

The USDR team has provided [content in a runbook format ](https://docs.google.com/document/d/1CyoA57KejbNEGhaLoLYlVTYkGER5h4RlSWzBE6xgd3g/edit#heading=h.ap3hp158d2we)to support the Open Source factor of our project. This body of work focuses on incorporating that content into our Grants Equity repo in sections such as, [README.md](https://github.com/HHS/grants-equity/blob/main/README.md), [CONTRIBUTING.md](https://github.com/HHS/grants-equity/blob/main/CONTRIBUTING.md).

This ticket is updating the Grants Equity repo README with the  [Core Team](https://docs.google.com/document/d/1CyoA57KejbNEGhaLoLYlVTYkGER5h4RlSWzBE6xgd3g/edit#bookmark=id.h8u4lot1gkaa) section from the OS runbook.

For this ticket, [CONTRIBUTING.md](https://github.com/HHS/grants-equity/blob/main/CONTRIBUTING.md) should be updated with the results of #185 and to incorporate content from the open source runbook.

### Acceptance criteria

- [ ] CONTRIBUTING.md is complete
- [ ] CONTRIBUTING.md incorporates #185 
- [ ] CONTRIBUTING.md incorporates open source runbook content
