### ISSUE TITLE
Milestone: API Planning

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#42]
### Description

Formalize a series of architectural decisions about the API, including the technology stack we will use, the type of API we will build, and the services we'll leverage to deploy and host it.

### Dependencies

None

### Sub-Tasks

- [x] #21 
- [x] #27 
- [x] #28 
- [x] #186 
- [x] #187 
- [x] #188  

### Definition of Done

- [x] The tools and services chosen have been authorized under the Grants.gov ATO (Authority to Operate) or FedRAMP approved
- [x] An ADR has been recorded and published to `main` for each of the following choices:
  - [x] API Language
  - [x] API Framework
  - [x] API Type
  - [x] API Deployment Service
- [x] Architecture diagram
  - [x] An initial architecture diagram for the backend has been published to the `main` branch of the repository
  - [x] The diagram is stored in a format that supports tracking individual changes with version control
