### ISSUE TITLE
[Task]: Migrate NOFO project plan to GitHub

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#443]
### Summary

Migrate the approved draft of the NOFO Project Plan from Excel to the [NOFO Project Tracker in GitHub](https://github.com/orgs/HHS/projects/14/views/3)

### Acceptance criteria

- [ ] All of the tasks and milestones in the Excel file have been transferred to GitHub with the corresponding fields updated
- [ ] The tasks and milestones have been converted into issues and with the appropriate labels applied
- [ ] An initial set of views and charts have been created to assist with creating the status report

**Comment by lucasmbrown-usds** [comment]
I would add: reviewed and approved by Elizabeth and Camille, with supporting reviews from Emily and Lucas.

**Comment by widal001** [comment]
This ticket is almost ready to close out, we're just waiting for some input about the visibility of the project and tasks.

**Comment by widal001** [comment]
We've officially moved project tracking to GitHub for NOFO workstream. Updates to tickets will happen as part of the update process.
