### ISSUE TITLE
[Task]: Demo of options for HHS internal comms site

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#446]
### Summary

Prepare a demo for the HHS team of options for the internal comms site and collaboration site for NOFO100. This demo should include a slide deck that outlines the requirements and options we're considering and (ideally) a mockup of what these various options could look like.

### TODO

- [x] @widal001 Create a mock site in GitBook
- [ ] @widal001 Create a mock site in SharePoint
- [x] @widal001 @HunterDHDH Create a slide deck which outlines the requirements and expected content for this site
- [x] @widal001 @HunterDHDH Present slide deck to Camille and Elizabeth for review and feedback

### Acceptance criteria

- [x] A slide deck which outlines the requirements and recommendations has been created and shared with HHS stakeholders
- [x] Mockups of the comms site have been created in the following tools:
  - [x] GitBook
  - [ ] SharePoint (if we can get a sandbox account)
- [x] The slide deck and mockups have been presented to HHS leadership and we've reached a decision
- [x] An ADR ticket has been created to record this decision once it's been finalized

**Comment by widal001** [comment]
Update the Google doc with the draft ADR for this choice. Make sure we split out HHS SharePoint vs Contractor SharePoint

**Comment by widal001** [comment]
We prepared a slide deck with some questions about the comms site, we'll be reviewing that slide deck sometime this week as a result it will carry over into the week of 9/11.

**Comment by widal001** [comment]
We presented this slide deck and a demo of GitBook on 9/14, we're leaning toward GitBook but need to investigate the cost implications of giving guest access to all of HHS staff. The final decision will be reflected in #498
