### ISSUE TITLE
[Task]: Train HHS staff on GitHub

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#449]
### Description

Add the HHS stakeholders on how to use and interact with the NOFO Project Tracker in GitHub.

### TODO

- [x] @sarahknoppA6 Schedule training with NOFO workstream leads
- [x] @widal001 Create training slide deck
- [x] @widal001 Add GitHub handles to the project
- [x] @widal001 Facilitate training

### Definition of Done

- [x] The following HHS stakeholders have created GitHub accounts and been added to the project:
  - [x] Camille
  - [x] Elizabeth
  - [x] Emily
  - [x] Julie
  - [x] Robert
  - [x] Dale
  - [x] Renee
- [x] Each of the stakeholders above has received a training on how to use the NOFO project tracker
- [x] The stakeholders can complete the following tasks on their own:
  - [x] Filtering a view for tasks with their name
  - [x] Commenting on a task
  - [x] Accessing the report
  - [x] Requesting changes to the project plan

**Comment by widal001** [comment]
Last week I started the slide deck for this training. This will carry over to the week of 9/11

**Comment by widal001** [comment]
Here's the link to the [training slide deck](https://docs.google.com/presentation/d/1bBrYZ_L8WE0lp82093OAjI0fWgFn6KIl/edit?usp=sharing&ouid=101063423102815364781&rtpof=true&sd=true)

**Comment by widal001** [comment]
Completed staff trainings yesterday
