### ISSUE TITLE
Milestone: DB planning

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#48]
### Description

Formalize a series of architectural decisions about how data is stored, including the type of database we will use and the platform we'll use host it.

### Dependencies

None

### Sub-Tasks

- [x] #104 
- [x] #142 

### Definition of Done

- [x] The tools and services chosen have been authorized under the Grants.gov ATO (Authority to Operate)
- [x] An ADR has been recorded and published to `main` for each of the following choices:
  - [x] Database Type
  - [x] Database Management System (DBMS)
  - [x] Database Hosting Service
