### ISSUE TITLE
Milestone: Front-end planning

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#49]
### Description

Formalize a series of architectural decisions about the frontend, including the technology stack we will use and the services we'll leverage to deploy and host it.

### Dependencies

None

### Sub-Tasks

- [x] #32 
- [x] #96 
- [x] #97 
- [x] #189 

### Definition of Done

- [x] The tools and services chosen have been authorized under the Grants.gov ATO (Authority to Operate) or is FedRAMP approved
- [x] An ADR has been recorded and published to `main` for each of the following choices:
  - [x] Front-end Language
  - [x] Front-end framework
  - [x] Front-end deployment service
  -
