### ISSUE TITLE
[Epic]: beta.grants.gov domain

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#51]
### Description

Gain access to the subdomain, beta.grants.gov. Prove access by deploying static test content (e.g., ipsum lorem) to that subdomain.

Once Nava has AWS console access, we can setup servers or a load balancer that has a dedicated IP address. Once we have that IP address, Julius or Lucas have the forms to request [beta.grants.gov](http://beta.grants.gov/) to direct to that IP address.

### Dependencies

Blocked by #139 

### Sub-Tasks

- [x] Setup servers or load balance 
- [x] Get dedicated IP address
- [x] Request to Julius or Lucas for the beta.grants.gov domain
- [x] #295 
- [x] #296
- [x] #384 

### Definition of Done

- [x] beta.grants.gov domain is set up and available
