### ISSUE TITLE
[30k]: Static site launch

### ISSUE THREAD

**Issue by widal001** [HHS/grants-equity#62]
### Description

**Milestone Doc:** [Static Site](https://github.com/HHS/grants-equity/blob/main/documentation/milestones/individual_milestones/static_site.md)

Launch a simple site at beta.grants.gov that provides static, informational content about the Grants Equity initiative, which includes both the Grants.gov Modernization and NOFO Transformation workstreams.

### Business Value and Description

The launch of a static site for the Grants Equity project represents the culmination of multiple internally focused deliverables and serves as a landing page where key stakeholders can access information about the project.

By sharing this information in a publicly accessible format and investing early in the infrastructure used to host it, this milestone aims to demonstrate the following value propositions:

- Raises awareness about the Grants Equity project, its priorities, and ongoing workstreams
- Establishes beta.grants.gov as the primary location that stakeholders can visit for project updates and previews of deliverables from each of the workstreams
- Proves the successful completion of technical milestones that enable faster development without sacrificing code quality or security
- Delivers an early win that both internal and external stakeholders can rally around, which helps build momentum and enthusiam for the project
- Facilitates a parallel approach to development, in which new features can be built and tested on beta.grants.gov without risking or disrupting the existing functionality of legacy grants.gov

### Dependencies

None

### Epics

- [x] #44 
- [x] #49
- [x] #50 
- [x] #91
- [x] #53
- [x] #123
- [x] #60  
- [x] #58 
- [x] #51 
- [x] #63 
- [x] #415 

### Definition of Done

- [x] The following infrastructure requirements are satisfied:
  - [x] The code needed to build and deploy the site is merged to main
  - [x]  The site is built and hosted with the tools selected in the https://github.com/HHS/grants-equity/issues/49
  - [x]  All code quality checks set up in the https://github.com/HHS/grants-equity/issues/50 are passing
  - [x]  The resources required to deploy and host the site are provisioned programmatically using the framework established in the https://github.com/HHS/grants-equity/issues/123
  - [x]  Code changes are deployed using the CI/CD pipeline set up in https://github.com/HHS/grants-equity/issues/58
- [x]  The following user experience (UX) requirements are satisfied:
  - [x]  Anyone can access a live version of the site at beta.grants.gov
  - [x]  The site adopts the UI principles and framework established in the https://github.com/HHS/grants-equity/issues/60
  - [x]  The site has completed 508 compliance review and tickets have been created for findings that need to be addressed
  - [x]  Web traffic data for the site is actively being collected by the framework implemented in the https://github.com/HHS/grants-equity/issues/63
  - [x]  Additional development tickets have been created for collecting other data needed to calculate the metrics below
- [x]  The following content requirements are satisfied:
  - [x] Site content is updated to match the [Figma mockup](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=0-1&mode=design) of the site.
  - [x]  All content is deployed to beta.grants.gov
  - [x]  (REMOVED) The site contains information about both the NOFO Transformation and Grants.gov Modernization workstreams
  - [x]  The content on the site has been been reviewed and approved by the relevant stakeholders within each workstream
  - [x]  The site also links to external resources related to the project (if they are available), including:
    - [x]  The legacy grants.gov site
    - [x]  The open source repository
    - [x]  The open source wiki
    - [x]  ~The open source chat~ (Not yet publicly available)
- [x]  ~Stretch goal: The site provides a mechanism to collect stakeholder feedback or questions~ (Scoped to a different deliverable)

**Comment by widal001** [comment]
### Update Summary

- **Target Release Date:** 9/26
- **Assumptions informing this target:**
  - The 9/26 launch will _not_ include a feedback form. This feature will be added in a subsequent release.
  - The 9/26 launch is conditional on security approval from ISSO
  - The 9/26 launch will include analytics if we can receive the analytics.usa.gov account ID in the next week. Otherwise analytics will be introduced in a subsequent release.


### Message from @sumiat on 8/29:

> We are planning to launch an initial version of the static site on 9/26. The first release will feature the four grant announcement prototypes and basic analytics. Although the site won’t include a feedback form initially as we’re navigating some ongoing PRA requirements, we’re excited to release this in a future version.
>
> We plan to host with AWS which aligns with our long-term plans and infrastructure. The biggest risk that would prevent us from launching on 9/26 are the security approval requirements from the security team. We’re actively working on this and have a meeting with the ISSO on 8/31 to understand what we need to ensure security compliance and inform next steps.
If there is a high level of effort for compliance on AWS, we can consider alternative hosting options like Github pages. However, the ISSO will also need to approve hosting through GH. We believe that the time saved by switching to Github Pages might not be significant if security requirements remain.
>
>One additional minor risk is obtaining an analytics account ID, but we can release without analytics if we do not receive that in time. We are still starting on the tag implementation and will just need to insert our account ID into the tag when we receive it.

**Comment by lucasmbrown-usds** [comment]
We could setup a temporary Google Analytics account as well, so we can have eyes on the number of visitors (i.e., letting us know if somehow word gets out and thousands of people start visiting) in the early days. Setting up GA as a generic google account user only takes a few minutes, if I recall correctly.

**Comment by sarahknoppA6** [comment]
Need to check on remediation of 508 finding.

**Comment by widal001** [comment]
This deliverable was reviewed on 10/19 and all of the acceptance criteria were met with the following small caveats:

- The open source chat was linked to the site (descoped because chat is not yet publicly available)
- The site provides a mechanism to collect stakeholder feedback or questions (descoped because this will be covered in #568 )

As a result, we're able to successfully marked this as completed

**Comment by widal001** [comment]
Updated the format of this ticket to reduce duplication of information between the ticket in GitHub and the deliverable spec in GitBook.
